### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by smfinvest** [kjvelarde/angular-multiselectsearchtree#11]
Thank you for the update for CSS. I have a question about the un-named version. When I do bower update I don't get that version. Does it need to be versioned with a number beyond 0.9.5?

When I run bower info kjvelarde-angular-multiselectsearchtree 
I get 
Available versions:
-0.9.0
-0.8.5
-0.8.0

**Comment by kjvelarde** [comment]
That was weird; apparently v1.0/v1.1 wasn't the right way to version it? I had to do a few test with versioning. 

The latest should be able in the repo now as v1.1.0. 

Thanks for letting me know about the issue.
