### ISSUE TITLE
Can i disable the search field? If yes, how?

### ISSUE THREAD

**Issue by LeandroVCastro** [kjvelarde/angular-multiselectsearchtree#4]
I don't need use the search field and i wanna disable it.
Can i do it?
How?

Thanks for the plugin, it's amazing :D 

(EDIT)
I tryed this way and is working... but i believe is not the best way
.tree-control .line{
    display: none;
}

Still waiting for suggestions

**Comment by kjvelarde** [comment]
Do you want the search box to show at all or just disable it?

**Comment by LeandroVCastro** [comment]
I would like disable and hidden it.

**Comment by kjvelarde** [comment]
Just updated. You can add attribute filter-type='hidden/disable' Thanks! - check the demo

**Comment by LeandroVCastro** [comment]
Thanks, bro
