### ISSUE TITLE
Issue: Alignment of top level element without children

### ISSUE THREAD

**Issue by smfinvest** [kjvelarde/angular-multiselectsearchtree#5]
We have played with the src/tree-item.tpl.html to allow for the better alignment of elements without children. 
Two requests: Can you make your source code available for 0.9.5. We would like to add to the directive the ability to use our own template url, much like the bootstrap directives work.

Much thanks for a really great tree directive!!!

**Comment by kjvelarde** [comment]
Just updated. Thanks!
