### ISSUE TITLE
kjvelarde-angular-multiselectsearchtree version problem

### ISSUE THREAD

**Issue by MounaME** [kjvelarde/angular-multiselectsearchtree#6]
I have this issue 👍 
17:05:33 bower kjvelarde-angular-multiselectsearchtree#0.8.0     ENORESTARGET No tag found that was able to satisfy 0.8.0
17:05:33 
17:05:33 Additional error details:
17:05:33 No versions found in https://github.com/kjvelarde/angular-multiselectsearchtree.git

My bower.json is like : "kjvelarde-angular-multiselectsearchtree" : "0.8.0"

**Comment by kjvelarde** [comment]
Sorry I wasn't tagging the commits. I just added them #0.8.0 #0.8.5 #0.9.0 

Thanks
