### ISSUE TITLE
Two selectors with same source, how to prevent duplicate selections?

### ISSUE THREAD

**Issue by ggulik** [kjvelarde/angular-multiselectsearchtree#9]
I would like to use two selectors on a page with the same source list.

However, if an item is selected on one selector it should be unavailable/disabled in the other selector, so each it can be selected only once.

Is that possible to do with this directive?  if so, how?

**Comment by kjvelarde** [comment]
I made the app to abstract its functions from the data manipulating/binding part of things. I had a project once that uses this component multiple times in the same page with multiple source and 1 final collection of the sources. In your scenario, you could create a watch/callback method that check the difference from technically 2 different collection/object but with the same signature/properties and manipulate it to reflect what you want its state to be. Thanks!
